### ISSUE TITLE
Rework setUseSimpleExpressions

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#18]
`TemplateLoader.setUseSimpleExpressions` is confusing and I'm not entirely sure what it *should* accomplish (seems like bad API design, the javadoc doesn't help either). Perhaps the method should entirely enable/disable expressions through something like `TemplateLoader.setEnableExpressions`, but one issue with this is that I don't think this covers the use case either. I would either want all of Horseshoe or none of it - things such as partial declarations would still be available. Perhaps `TemplateLoader.setMustacheCompatibility` would be a better method name, but what does Mustache compatibility even mean? In any case this would require a substantial refactor of the parser.

So my questions are (and the goal of this issue to be resolved):
 1. Is there still a design goal of supporting vanilla Mustache?
 2. What's the use case for `TemplateLoader.setUseSimpleExpressions`?
 3. If `TemplateLoader.setUseSimpleExpressions` is removed, what should it be replaced with if anything?

**Comment by nicklauslittle** [comment]
1. I definitely think supporting vanilla Mustache is useful. There are plenty of Mustache tests that can be leveraged, and it helps that many people will recognize the Mustache tags.
2. The original idea was to just split everything on the '.' character for simple expressions, so there wouldn't be any confusion as to how some text is being parsed.
3. See below.

What if we did something like `TemplateLoader.setHorseshoeExtensions(int extensions)`, and then have bitmasked `int`s for `ENABLE_EXPRESSIONS`, `ENABLE_EMPTY_CLOSE_TAGS`, `ENABLE_NAMED_EXPRESSIONS`, `ENABLE_ALL_EXTENSIONS`, `DISABLE_ALL_EXTENSIONS`, `ENABLE_ELSE_TAGS`, `ENABLE_LOCAL_PARTIALS`, etc. Most people would likely choose to enable all extensions or disable all extensions, but it would allow people to customize which extensions were available.

Another option would be to only allow all or nothing (`TemplateLoader.setHorseshoeExtensions(bool enable)`). I'm not sure I have a preference. They both would require about the same amount of work. Not insignificant, but probably not as significant as you are thinking.

**Comment by tbateson** [comment]
I find it hard to imagine a scenario where only certain features are enabled. I don't think it is something that would be used enough to warrant such an inclusion. As far as method names go, I would prefer something like `TemplateLoader.setEnableHorseshoeExtensions(boolean enableHorseshoeExtensions)`
