### ISSUE TITLE
Add support for local variables in expressions

### ISSUE THREAD

**Issue by nicklauslittle** [nicklauslittle/horseshoe-j#21]
See PR #20.

The idea behind this is that it would be useful to have some way to store data temporarily inside an expression, so that it can be referenced multiple times within the expression. (Example: `{{ value = ./blah[0].getObject()?.getValue(); value?.isCool() ? value.getPositiveValue() : 0 }}`)

Local variables only exist within the current expression and cannot be referenced via other expressions. Also, any identifier that starts with `./` references the current context and not a local variable. Thoughts?

**Comment by tbateson** [comment]
Two questions:
 1. What would the output of `{{value = 1}}` be "" or "1"?
 2. Can variables "escape" tags? such as `{{value = 1}}{{value}}`?

**Comment by nicklauslittle** [comment]
1. 1, assignments always return `rvalue`s of the assigned variable.
2. No, local variables are scoped to a single expression (tag in this sense).
