### ISSUE TITLE
Dynamic class-loading operator

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#25]
Currently there is no "good" way of performing on-demand class-loading from a pure Horseshoe templating perspective. Unless you provide every class explicitly in your Java code, you cannot invoke static methods or use classes which are no available. There are several cases in code where I need to do something like convert a `String` to `int` (`Integer.parseInt(String)`), or check if a Horseshoe array contains a certain element (`Arrays.asList(T[]).contains(T)`).

I have a good solution to this problem: the `$` unary operator. The `$` operator operates much like the `-` unary operator, in this case it converts a `java.lang.String` into a `java.lang.Class`.

Example:
 - `$"java.lang.Integer".parseInt("123")` &rarr; `123`

The `$` operator would need to be precedence 0. It would probably suffice to implement the `$` operator with `java.lang.ClassLoader.getSystemClassLoader().loadClass(String)`

**Comment by nicklauslittle** [comment]
I like the idea, but I fear this will be a security nightmare. This would provide access to all sorts of I/O, class-loading, reflection, etc. We may need to have a white-list of allowed classes. Any thoughts on an initial list or proposed alternatives?

**Comment by tbateson** [comment]
Technically all `Class<?>` have access to a classloader through `Class.getClassLoader()`. However, every class loaded by the bootstrap classloader return `null` for the above method, but you could potentially have a class that wasn't loaded by the bootstrap giving you access to the `loadClass` method.

As far as whitelisting is concerned, we could start with `java.util.*` and `java.lang.*` - except for `java.lang.ClassLoader` and allow the user to specify their own pattern.
