### ISSUE TITLE
Declaring errors in templates

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#28]
Some templates may require that an error be thrown if a certain condition is met. This could be a missing data member or perhaps another condition. Currently there is no way to throw an exception that "escapes" the Horseshoe parser because all exceptions are caught by `Expression.java:915`.

My suggestion is to add a sort of "exception literal" such as the currently unused apostrophe `'`. This literal would function like parenthesis, but it would capture the value of an expression as an exception. For example `'"This is an exception: " + myVariable.toString()'`. These "exception literals" would construct a new Java exception class `TemplateException` that is thrown by the `Template.render` method. "Exception literals" are only thrown if they are the return value of an expression, therefore the expression `{{'"This is an unthrown exception"'; "Hello world!"}}` would not throw an `TemplateException`.

More specifically the syntax would be: `'` `Expression` `'`.

**Comment by nicklauslittle** [comment]
Implemented
