### ISSUE TITLE
Recursive named expressions

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#31]
I created a simple recursive named expression test that calculates the Fibonacci sequence for a given input number, `{{fib -> . > 1 ? fib(. - 1) + fib(. - 2) : .}}`. `{{fib(0)}}` and `{{fib(1)}}` both return the correct values, all other results are empty. See 5741f9d5f.

**Comment by nicklauslittle** [comment]
Fixed.
