### ISSUE TITLE
Post-increment and pre-increment in ternary sometimes fails parsing

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#34]
See `TernaryTests.java` in 727024144da293. There are cases where ternaries successfully parse with post-increment, but in other cases it fails with an error such as `Invalid tag "indexOf -> index < length ? a[index] == value ? index : (dummy = 0; index++; indexOf(.)) : -1" at character 3`. Others such as `{{b = 111; x = value ? (a = 123; b = 345; b = 456; b == 345 ? a + b : (b++; b = 123; a + b)) : null; b + x}}` manages to parse and execute correctly.

**Comment by nicklauslittle** [comment]
I looked through these tests and they are not valid. They fail to parse because there is no assignment to the value index before you try to increment it.

**Comment by nicklauslittle** [comment]
I'm thinking about removing all the assignment operators except for the `=` operator. This way there would never be parse errors related to trying to modify a local variable that hasn't been assigned to yet. Thoughts?
