### ISSUE TITLE
Rework Collections

### ISSUE THREAD

**Issue by nicklauslittle** [nicklauslittle/horseshoe-j#47]
Rework the collections available using the `[]` and `{}` operators. Proposal is as follows:

- `[1, 2, 3]`: `List` (`ArrayList`) [Change from array to `List`]
- `[a:b, c:d]`: `Map` (`LinkedHashMap`) [Remove iteration, iteration would require invoking `.entrySet()`]
- `{1, 2, 3}`: `Set` (`LinkedHashSet`) [Change from array to `Set`]
- `{a:b, c:d}`: `Map` (`LinkedHashMap`)

This syntax closely aligns with syntax from other modern scripting languages, like python.

Another potential change would be to allow any Set or Map literal starting with `{` to end with `]` instead of `}`. The idea is that using `]` would not confuse the Mustache tag parser when locating the end of a Mustache tag (`}}`).

**Comment by tbateson** [comment]
Agree with `[1, 2, 3]` and `[a:b, c:d]`. I don't see any reason to support alternative syntax for `{a:b, c:d}` as it doesn't support any new functionality and as you pointed out can cause confusion. I definitely do not like having `{` closed by `]` as I don't see that as any less confusing.

Not sure what to do about sets, not even sure if set literals are necessary.
