### ISSUE TITLE
Feature Request: support for annotation markers in templates

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#5]
Assume I have the data file:
```json
{ "data": [{
  "type": { "dir1": "a", "dir2": "b", "value": 0}
}, {
  "type": { "dir1": "c", "dir2": "d", "value": 1}
}]}
```
And the template:
```handlebars
{{#data}}
{{#@file={{dir1}}/{{dir2}}.cpp}}
int main() { return {{value}}; }
{{/@file}}
{{/data}}
```

This would produce two files, `a/b.cpp` with contents `int main() { return 0; }` and `c/d.cpp` with contents `int main() { return 1; }`. This functionality would need to be programmed into the runner using the Horseshoe template engine.

This would introduce two new syntaxes: `{{#@<variable-name>}}...{{/@<variable-name}}` and `{{@<variable-name>}}`

The semantics of this feature would be akin to annotations in Java, they would mark information with a name but would do nothing aside from that. In order to support this, changes to the `Template.render` method would be necessary, potential options are overloading the method with `Template.render(..., AnnotationHandler)`.

AnnotationHandler may look something like:
```java
public interface AnnotationHandler {
  public Writer handleAnnotation(final String annotationValue);
}
```

The rough idea is that an annotation handler returns back a writer which consumes the contents of the annotation.

**Comment by nicklauslittle** [comment]
I've had some trouble figuring out how to implement nested tags, so I came up with a work around to support a similar concept. It uses a callback like the one you've created and functions pretty much the same way, except it uses `>` instead of `@` (I'm thinking you are basically redirecting output as in `echo "blah" >&2`).

It doesn't use nested tags, so the template is a little bit uglier:
```handlebars
{{dir1}}/{{dir2}}.cpp
{{#>RedirectToFile}}
int main() { return {{value}}; }
{{/>RedirectToFile}}
```
and then when invoking the engine (in java):
```java
final java.io.Writer writers[] = new java.io.Writer[] { new java.io.StringWriter(), null };
template.render(settings, data, writers[0], new Template.WriterMap() {
	@Override
	public Writer getWriter(final String name) {
		if ("OutputToFile".equals(name)) {
			try {
				return writers[1] = new java.io.FileWriter(writers[0].toString().trim());
			} catch (final IOException e) {
			}
		}

		return null; // Keep using whatever writer was being used
	}
});
```
Let me know what you think.

**Comment by tbateson** [comment]
One issue I take with `>` is that in normal bash terms it redirects output, which is not the purpose of this feature (and why I prefer `@`). I like the idea of using `{{#> stderr}}...{{/stderr}}` in order to log information, but this has a very lambda-y feeling (consuming input / changing the output) which I do not want to get into.

Perhaps a better way of handling this is just through simple callbacks:
```java
new TemplateLoader()
  .registerAnnotation("file", new AnnotationHandler() {
    @Override
    public void handle(String annotationName, CharSequence content) {
      // ...
    }
  });
```
An important goal of this is to allow the template runner to execute the annotation handlers in parallel alongside template rendering.

**Comment by nicklauslittle** [comment]
Check out the latest commit and see if you like it. Examples are in TemplateTests.java.

**Comment by tbateson** [comment]
I made some changes to the backend implementation. See #10. Notable changes include annotations send output to both the original and new writers and allowing for annotations to be processed in parallel (right now joining occurs at the end of `Template.render`, which is not optimal).

**Comment by nicklauslittle** [comment]
Looked at it. What is the intent of writing to both the original and new writer?

I'm thinking that if we do parallel processing of sections we should use a custom interface for executors. The ExecutorService interface is too unusable for what we need.
