### ISSUE TITLE
Feature Request: locally scoped partial in template

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#6]
Proposed usage:
```handlebars
{{< f}}{{a}}{{/f}}
```
declares a local partial whose name is `f`.

Invoking the local partial: `{{> f}}` (like a normal partial).

Finer details:
- Local partials are only available within the scope they are declared; `{{#a}}{{< f}}{{.}}{{/f}}{{/a}}{{> f}}` is an error (or no output depending on configuration).
- Local partials do not extend back; `{{> f}}{{< f}}{{a}}{{/f}}` is an error.
- Local partials may not override local data, global data, local partials, or global partials; doing so is an error.

**Comment by nicklauslittle** [comment]
I'm curious about the last point. To me it makes more sense to have the local partials override any existing local partials or global partials. Have a look at what I've added. If it doesn't meet your needs, let me know.

**Comment by tbateson** [comment]
I've taken a look and after further review there doesn't seem to be a need to throw an error if partials and data collide.
